# Generated by Django 3.1 on 2022-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('L', 'Laptops'), ('P', 'Phones'), ('W', 'Watches'), ('A', 'Accessories'), ('R', 'Realme'), ('Op', 'Oppo'), ('On', 'OnePlus')], max_length=2, null=True),
        ),
    ]
