# Generated by Django 3.0.5 on 2022-06-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20220613_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itm_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
