# Generated by Django 3.0.5 on 2022-06-13 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_item_itm_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itm_code',
            new_name='item_code',
        ),
    ]
